#!/usr/bin/env bash
# Summary: Display all versions of Go installed.

# Bomb out if we hit an error, ever
set -e

# Iterate over installed versions and write to output
if [ -d "/usr/local/go" ]; then
    echo "system"
fi
for path in "${GOBREW_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    echo "${path##*/}"
  fi
done
