#!/usr/bin/env bash
# Summary: Specify which go version to use.

set -e
[ -n "$GOBREW_DEBUG" ] && set -x

#if [ "$1" = "--complete" ]; then
#    echo system
#    exec gobrew-versions --bare
#fi

version="$1"
VERSIONS=`ls -l $GOBREW_ROOT/versions | egrep '^d' | awk '{print $9}'`

for v in $VERSIONS
do
    if [ -z $version ]; then
        echo "gobrew: please specifiy version to use."
        exit 0
    elif [ "$v" = $version ]; then
        echo $version > "$GOBREW_ROOT/version"
        exit 1
    fi
done
 
if [ "system" = $version ] && [ -d "/usr/local/go" ]; then
    echo $version > "$GOBREW_ROOT/version"
    exit 1
fi

echo "gobrew: $version not installed."
exit 0
