#! /usr/bin/env bash
# Summary: Install a version of go. example: gobrew install 1.1.2


set -e

[ -n "$GOBREW_DEBUG"] && {
    set -x
}

version="$1"
version_dir="$GOBREW_ROOT/versions/$version"

OLDPWD=$(pwd)

mkdir -p "$version_dir"
cd "$version_dir"

platform="$(uname -s | tr '[:upper:]' '[:lower:]')"



if [ "$(uname -m)" = "x86_64" ]; then
    arch="amd64"
else
    arch="386"
fi

if [ -z "$version" ]; then
    echo "Must specify version"
    exit 1
fi

# Allow the GO_FILES_URL environment variable override the location of the
# go installation files
files_url=${GO_FILES_URL:=https://storage.googleapis.com/golang/}

# Check for Mac OS X.
version_major="$(echo $version | cut -d . -f 1)"
version_minor="$(echo $version | cut -d . -f 2)"

if [ $platform = "darwin" -a $version_minor -gt 1 ]; then
    if [ $version_minor -gt 4 ]; then
        file_name="go${version}.${platform}-${arch}.tar.gz"
    else
        darwin_major="$(uname -r | cut -d . -f 1)"

        if [ $darwin_major -lt 11 ]; then
            file_name="go${version}.${platform}-${arch}-osx10.6.tar.gz"
        else
            file_name="go${version}.${platform}-${arch}-osx10.8.tar.gz"
        fi
    fi
else
    file_name="go${version}.${platform}-${arch}.tar.gz"
fi

download=$files_url$file_name

set +e

(
    if type wget &>/dev/null; then
        echo "Installing $file_name"
        wget -P "$GOBREW_ROOT/cache" "${download}"
        tar -zxf "$GOBREW_ROOT/cache/$file_name" --strip-components 1
    elif type curl &>/dev/null; then
        echo "Installing $file_name"
        curl -s -f "$download" > "$GOBREW_ROOT/cache/$file_name"
        tar -zxf "$GOBREW_ROOT/cache/$file_name" --strip-components 1
    else
        echo "error: please install \`curl\` or \`wget\` and try again" >&2
        exit 1
    fi
    rm "$GOBREW_ROOT/cache/$file_name"
) || \
    {
        cd $OLDPWD
        rm -rf "$version_dir"

        echo "gobrew: unable to install ${version} from binary, download not available"
        exit 1
    }

echo "Installed ${version}"
cd $OLDPWD

exec "${GOBREW_ROOT}/bin/gobrew" rehash
