#! /usr/bin/env bash
# Summary: List available versions of go. example: gobrew list


set -e

[ -n "$GOBREW_DEBUG"] && {
    set -x
}

platform="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [ "$(uname -m)" = "x86_64" ]; then
  arch="amd64"
else
  arch="386"
fi

echo "finding Go versions for $platform-$arch"

# Allow the GO_DOWNLOADS_URL_LIST environment variable override the location of the
# go installation files
url=${GO_DOWNLOADS_LIST_URL:=https://code.google.com/p/go/downloads/list?can=1&num=10000}
go_downloads_list=$url
curl -s $go_downloads_list \
| grep "<a href=\"//.*/files/go.*\.tar\.gz" \
| sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' \
| sed -n 's/.*files\/\(go.*\.tar\.gz\)/\1/p' \
| sed -n "s/go\(.*\)\.$platform-$arch.*/\1/p" \
| uniq \
| sort
