#!/usr/bin/env bash
# Summary: Accepts two commands set and unset 'gobrew workspace set' sets your current working directory as your workspace($GOPATH). 'gobrew workspace' displays what workspace has been set.

set -e

[ -n "$GOBREW_DEBUG" ] && {
    set -x
}

    

if [ -z "${GOBREW_WORKSPACE}" ]; then
    GOBREW_WORKSPACE_FILE="$(gobrew-workspace-file)"
    GOBREW_WORKSPACE="$(gobrew-workspace-file-read "$GOBREW_WORKSPACE_FILE" || true)"
fi

if [ -n "$1" ]; then
    if [ "$1" = "set" ]; then
        echo "$(pwd)" >> "$GOBREW_WORKSPACE_FILE"
        export GOPATH="$(pwd)"
        export PATH="GOPATH/bin:$PATH"
        exit 1
    elif [ "$1" = "unset" ];then
        $(cat /dev/null > $GOBREW_WORKSPACE_FILE)
        echo "gobrew: Go workspace cleared."
        unset GOPATH
        exit 1
    fi
fi

workspace_exists() {
    local workspace="$1"
    [ -d "${workspace}" ]
}

if workspace_exists "$GOBREW_WORKSPACE"; then
    echo "$GOBREW_WORKSPACE"
fi
