#!/usr/bin/env bash
# Summary: Detect the file that sets the current gobrew version

# Bomb out if we hit an error, ever
set -e

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ ! -d "${root}/gobrew_version" ] && [ -e "${root}/gobrew_version" ]; then
      echo "${root}/gobrew_version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$GOBREW_DIR"
[ "$GOBREW_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${GOBREW_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
fi
