#!/usr/bin/env bash
set -e
[ -n "$GOBREW_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${GOBREW_ROOT}" ]; then
  GOBREW_ROOT="${HOME}/.gobrew"
else
  GOBREW_ROOT="${GOBREW_ROOT%/}"
fi
export GOBREW_ROOT

if [ -z "${GOBREW_DIR}" ]; then
  GOBREW_DIR="$(pwd)"
else
  cd "$GOBREW_DIR" 2>/dev/null || {
    echo "gobrew: cannot change working directory to \`$GOBREW_DIR'"
    exit 1
  } >&2
  GOBREW_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export GOBREW_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${GOBREW_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${GOBREW_HOOK_PATH}:${GOBREW_ROOT}/gobrew.d:/usr/local/etc/gobrew.d:/etc/gobrew.d:/usr/lib/gobrew/hooks"
for plugin_hook in "${GOBREW_ROOT}/plugins/"*/etc/gobrew.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export GOBREW_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(gobrew---version)\n$(gobrew-help)" >&2
  ;;
"-v" )
  exec gobrew---version
  ;;
* )
  command_path="$(command -v "gobrew-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "gobrew: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
