#!/usr/bin/env bash
# Summary: Run 'gobrew workspace set' from your workspace folder to set as $GOPATH.
#
# Usage: 'gobrew workspace' 'gobrew workspace set' 'gobrew workspace unset'

set -e

[ -n "$GOBREW_DEBUG" ] && {
    set -x
}

    

if [ -z "${GOBREW_WORKSPACE}" ]; then
    GOBREW_WORKSPACE_FILE="$(gobrew-workspace-file)"
    GOBREW_WORKSPACE="$(gobrew-workspace-file-read "$GOBREW_WORKSPACE_FILE" || true)"
fi


if [ -n "$1" ]; then
    if [ "$1" = "set" ]; then

        $(cat /dev/null > $GOBREW_WORKSPACE_FILE)
        echo "$(pwd)" >> "$GOBREW_WORKSPACE_FILE"
        echo 'export GOPATH="'$(pwd)'"'
        echo 'export PATH="'$(pwd)'/bin:$PATH"'
        echo "gobrew: Please close and repoen terminal window."
        exit 1
    elif [ "$1" = "unset" ];then

        $(cat /dev/null > $GOBREW_WORKSPACE_FILE)
        echo "gobrew: Go workspace cleared."
        unset GOPATH
        exit 1
    fi
fi

workspace_exists() {
    local workspace="$1"
    [ -d "${workspace}" ]
}

if workspace_exists "$GOBREW_WORKSPACE"; then
    echo "$GOBREW_WORKSPACE"
fi
